# -------------------------------
# SERVER CONFIGURATION
# -------------------------------

server.port=8081
server.address=0.0.0.0

# -------------------------------
# H2 DATABASE CONFIGURATION
# -------------------------------

spring.datasource.url=jdbc:h2:mem:journeymanager
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# -------------------------------
# JPA / HIBERNATE
# -------------------------------

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create


# -------------------------------
# H2 CONSOLE
# -------------------------------

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# -------------------------------
# LOGGING (VERY USEFUL FOR DEBUG)
# -------------------------------

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE